name: PR Checks

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
      - '**/docs/**'
      - '**/*.txt'

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Detect non-comment code changes
        id: changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          diff_lines=$(git diff --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | \
            grep -E '^[+-](?![+-])' | \
            grep -vE '^[+-]\s*(//|#|/\*|\*|<!--)' | wc -l)
          if [ "$diff_lines" -gt 0 ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi
      - if: steps.changes.outputs.run == 'true'
        run: npm install
      - if: steps.changes.outputs.run == 'true'
        run: npm run lint
      - if: steps.changes.outputs.run == 'true'
        run: npm run type-check
      - if: steps.changes.outputs.run == 'true'
        run: npm run build
      - if: steps.changes.outputs.run == 'true'
        run: npm test
      - if: steps.changes.outputs.run == 'false'
        run: echo "Only comment or documentation changes detected. Skipping checks."
